from core.exceptions import BaseAppException


class UnexpectedErr1(BaseAppException):
    pass

class UnexpectedErr2(BaseAppException):
    pass